routes/web.php
<?php

//===============================
// Routes For Front end Goes Here
//===============================

Route::get('/login', 'PageController@index')->name('login');
Route::get('/logout', 'PageController@index')->name('logout');

Route::prefix('/')->group(function (){

    // page route
    Route::get('/', 'PageController@index')->name('page.index');
    Route::get('/about', 'PageController@about')->name('page.about');
    Route::get('/gallery', 'PageController@gallery')->name('page.gallery');
    Route::get('/executive', 'PageController@executives')->name('page.executive');
    Route::get('/report', 'PageController@report')->name('page.report');
    Route::get('page/register', 'PageController@register')->name('page.register');
    Route::get('/school/info', 'PageController@schoolInfo')->name('sch.info');

    // get records
    Route::get('/executive/users', 'PageController@getExecutives');
    Route::get('/all/posts', 'PageController@getAllPost');
    Route::get('/all/gallery', 'PageController@getAllGallery');
    Route::get('/latest/posts', 'PageController@getLatestPost');
    Route::get('/all/classes', 'PageController@getClasses');
    Route::get('/all/subjects', 'PageController@getSubject');
    Route::get('/all/levels', 'PageController@getLevel');
    Route::get('/all/region', 'PageController@getRegion');
    Route::get('/all/about', 'PageController@getAbout');
    Route::get('/all/carousel', 'PageController@getCarousel');
    Route::get('/all/report', 'PageController@getAllReport');
    Route::get('/get/advert', 'PageController@getAdvert');


    // get with id
    Route::get('/all/district/{id}', 'PageController@getDistrict');
    Route::get('/all/zonal/{id}', 'PageController@getZone');
    Route::get('/view/post/{id}', 'PageController@viewPost');
    Route::get('/single/post/{id}', 'PageController@getPost');
    Route::get('/single/comment/{id}', 'PageController@getComment');
    Route::get('/single/gallery/{id}', 'PageController@getGallery');


    //update records
    Route::post('/update/statistic', 'AdminController@updateStatisticClasses');
    Route::post('/update/head', 'AdminController@updateSchoolHead');
    Route::post('/update/school_register', 'AdminController@updateSchoolRegister');
    Route::post('/update/school_book', 'AdminController@updateSchoolTextBook');



    // post route
    Route::post('/user/login', 'PageController@userLogin');
    Route::post('/save/message', 'PageController@sendMessage');
    Route::post('/save/comment', 'PageController@sendComment');
    Route::post('/save/users', 'PageController@saveUsers');
    Route::post('/save/school', 'PageController@saveSchool');
    Route::post('/save/classes/statistics', 'PageController@saveClasses');
    Route::post('/save/heads/info', 'PageController@saveSchoolHead');
    Route::post('/save/school/textbooks', 'PageController@saveSchoolTextBook');
    Route::post('/save/school/register', 'PageController@saveSchoolRegister');
    Route::post('/save/school/id', 'PageController@getSchoolID');


    // view route using id
    Route::get('/view/school/info/{id}', 'PageController@viewSchool');
    Route::get('/view/school/student/{id}', 'PageController@viewStudents');
    Route::get('/view/school/head/{id}', 'PageController@viewSchoolHead');
    Route::get('/view/school/register/{id}', 'PageController@viewSchoolRegister');
    Route::get('/view/school/levels/{id}', 'PageController@viewSchoolClassLevels');
    Route::get('/view/school/books/{id}', 'PageController@viewSchoolBook');


});

Route::group(['middleware' => ['auth', 'Admin']], function(){

    Route::prefix('/admin')->group(function (){

        // page route
        Route::get('/index', 'AdminController@index')->name('admin.index');
        Route::get('/executive', 'AdminController@executive')->name('admin.executive');
        Route::get('/loc/region', 'AdminController@region')->name('admin.region');
        Route::get('/loc/district', 'AdminController@district')->name('admin.district');
        Route::get('/loc/zonal', 'AdminController@zonals')->name('admin.zonal');
        Route::get('/post', 'AdminController@post')->name('admin.post');
        Route::get('/message', 'AdminController@message')->name('admin.message');
        Route::get('/sch/classes', 'AdminController@classes')->name('admin.classes');
        Route::get('/sch/levels', 'AdminController@level')->name('admin.level');
        Route::get('/sch/subject', 'AdminController@subject')->name('admin.subject');
        Route::get('/sch/owners', 'AdminController@schoolOwner')->name('admin.owner');
        Route::get('/about', 'AdminController@aboutus')->name('admin.aboutus');
        Route::get('/carousel', 'AdminController@carousel')->name('admin.carousel');
        Route::get('/sch/schools', 'AdminController@allSchool')->name('admin.school');
        Route::get('/sch/add', 'AdminController@addSchool')->name('admin.school.add');
        Route::get('/rep/report', 'AdminController@addReport')->name('admin.report');
        Route::get('/rep/gen_report', 'AdminController@generateReport')->name('admin.gen.report');
        Route::get('/rep/advert', 'AdminController@advert')->name('admin.advert');


        // get routes
        Route::get('/get/users', 'AdminController@getUsers');
        Route::get('/get/regions', 'AdminController@getRegion');
        Route::get('/get/districts', 'AdminController@getDistrict');
        Route::get('/get/zonals', 'AdminController@getZonal');
        Route::get('/get/posts', 'AdminController@getPost');
        Route::get('/get/messages', 'AdminController@getMessage');
        Route::get('/get/classes', 'AdminController@getClasses');
        Route::get('/get/subject', 'AdminController@getSubject');
        Route::get('/get/level', 'AdminController@getLevel');
        Route::get('/get/about', 'AdminController@getAbout');
        Route::get('/get/member', 'AdminController@getMember');
        Route::get('/get/carousel', 'AdminController@getCarousel');
        Route::get('/get/all_schools', 'AdminController@getSchools');
        Route::get('/get/all_users', 'AdminController@getAllUser');
        Route::get('/get/all_report', 'AdminController@getAllReport');
        Route::get('/get/all_advert', 'AdminController@getAdvert');


        // get with id
        Route::get('/get/comment/{id}', 'AdminController@getComment');
        Route::get('/get/gallery/{id}', 'AdminController@getGallery');
        Route::get('/update/message/{id}', 'AdminController@updateMessage');
        Route::get('/update/school/{id}', 'AdminController@updateSchoolMember');
        Route::get('/update/member/{id}', 'AdminController@updateSchoolGnaps');
        Route::get('/sch/schools/view/{id}', 'AdminController@viewSchoolDetail');
        Route::get('/membership/schools/{id}', 'AdminController@getMemberSchool');


        // save records
        Route::post('/save/user', 'AdminController@saveUsers');
        Route::post('/save/region', 'AdminController@saveRegion');
        Route::post('/save/district', 'AdminController@saveDistrict');
        Route::post('/save/zonal', 'AdminController@saveZonal');
        Route::post('/save/post', 'AdminController@savePost');
        Route::post('/save/classes', 'AdminController@saveClasses');
        Route::post('/save/subject', 'AdminController@saveSubject');
        Route::post('/save/level', 'AdminController@saveLevel');
        Route::post('/save/about', 'AdminController@saveAbout');
        Route::post('/save/carousel', 'AdminController@saveCarousel');
        Route::post('/save/owners', 'AdminController@saveSchoolOwner');
        Route::post('/save/report', 'AdminController@saveReport');
        Route::post('/save/advert', 'AdminController@saveAdvert');


        // update records
        Route::post('/update/user', 'AdminController@updateUsers');
        Route::post('/update/region', 'AdminController@updateRegion');
        Route::post('/update/district', 'AdminController@updateDistrict');
        Route::post('/update/zonal', 'AdminController@updateZonal');
        Route::post('/update/post', 'AdminController@updatePost');
        Route::post('/update/classes', 'AdminController@updateClasses');
        Route::post('/update/subject', 'AdminController@updateSubject');
        Route::post('/update/level', 'AdminController@updateLevel');
        Route::post('/update/profile', 'AdminController@updateProfile');
        Route::post('/update/password_change', 'AdminController@updateChangePassword');
        Route::post('/update/about', 'AdminController@updateAbout');
        Route::post('/update/carousel', 'AdminController@updateCarousel');
        Route::post('/update/owners', 'AdminController@updateSchoolOwner');
        Route::post('/update/school', 'AdminController@updateSchool');
        Route::post('/update/report', 'AdminController@updateReport');
        Route::post('/update/statistic/class', 'AdminController@updateStatisticClasses');
        Route::post('/update/head/info', 'AdminController@updateSchoolHead');
        Route::post('/update/school_register', 'AdminController@updateSchoolRegister');
        Route::post('/update/school_book', 'AdminController@updateSchoolTextBook');
        Route::post('/update/advert', 'AdminController@updateAdvert');


        // Delete records
        Route::delete('/delete/user/{id}', 'AdminController@deleteUser');
        Route::delete('/delete/region/{id}', 'AdminController@deleteRegion');
        Route::delete('/delete/district/{id}', 'AdminController@deleteDistrict');
        Route::delete('/delete/post/{id}', 'AdminController@deletePost');
        Route::delete('/delete/zonal/{id}', 'AdminController@deleteZonal');
        Route::delete('/delete/gallery/{id}', 'AdminController@deleteGallery');
        Route::delete('/delete/comment/{id}', 'AdminController@deleteComment');
        Route::delete('/delete/message/{id}', 'AdminController@deleteMessage');
        Route::delete('/delete/classes/{id}', 'AdminController@deleteClasses');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $table = 'posts';


    protected $fillable = [
        'title', 'body'
    ];

    public function getImageAttribute($value){
        return asset('/images/gallery/'.$value);
    }
}

resources/views/Partials/admin/_aside.blade.php
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
            <li class="{{ strtolower(Request::segment(2)) == 'index'?'active':''}}">
                <a class="" href="{{ route('admin.index') }}">
                    <i class="icon_house_alt" style="color: #ffb505"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="fa fa-location-arrow" style="color: #c0e3ff"></i>
                    <span>Location</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub" style="{{strtolower(Request::segment(2)) == 'loc'?'display:block':''}}">
                    <li class="{{ strtolower(Request::segment(3)) == 'region'?'active':''}}">
                        <a class="" href="{{ route('admin.region') }}">
                            <i class="fa fa-refresh" style="color: #0f2bff"></i>
                            <span>Regions</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'district'?'active':''}}">
                        <a class="" href="{{ route('admin.district') }}">
                            <i class="fa fa-th" style="color: #ff0e33"></i>
                            <span>Districts</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'zonal'?'active':''}}">
                        <a class="" href="{{ route('admin.zonal') }}">
                            <i class="fa fa-rss" style="color: #13ff62"></i>
                            <span>Zonals</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="{{ strtolower(Request::segment(2)) == 'executive'?'active':''}}">
                <a class="" href="{{ route('admin.executive') }}">
                    <i class="fa fa-user" style="color: #11fffe"></i>
                    <span>Executives</span>
                </a>
            </li>
            <li class="{{ strtolower(Request::segment(2)) == 'post'?'active':''}}">
                <a class="" href="{{ route('admin.post') }}">
                    <i class="fa fa-hand-pointer-o" style="color: #ffd6d8"></i>
                    <span>Posts</span>
                </a>
            </li>
            <li class="{{ strtolower(Request::segment(2)) == 'message'?'active':''}}">
                <a class="" href="{{ route('admin.message') }}">
                    <i class="fa fa-mail-reply" style="color: #5bffb8"></i>
                    <span>Messages</span>
                </a>
            </li>
            <li class="{{ strtolower(Request::segment(2)) == 'about'?'active':''}}">
                <a class="" href="{{ route('admin.aboutus') }}">
                    <i class="fa fa-history" style="color: #645fff"></i>
                    <span>About Gnaps</span>
                </a>
            </li>
            <li class="{{ strtolower(Request::segment(2)) == 'carousel'?'active':''}}">
                <a class="" href="{{ route('admin.carousel') }}">
                    <i class="fa fa-file-picture-o" style="color: #ebff07"></i>
                    <span>Carousel</span>
                </a>
            </li>

            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="fa fa-graduation-cap" style="color: #ff117f"></i>
                    <span>Schools</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub" style="{{strtolower(Request::segment(2)) == 'sch'?'display:block':''}}">
                    <li class="{{ strtolower(Request::segment(3)) == 'classes'?'active':''}}">
                        <a class="" href="{{ route('admin.classes') }}">
                            <i class="fa fa-clone" style="color: #1dddff"></i>
                            <span>Classes</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'subject'?'active':''}}">
                        <a class="" href="{{ route('admin.subject') }}">
                            <i class="fa fa-bookmark" style="color: #f2beff"></i>
                            <span>Subjects</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'levels'?'active':''}}">
                        <a class="" href="{{ route('admin.level') }}">
                            <i class="fa fa-leaf" style="color: #0eff10"></i>
                            <span>Levels</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'schools'?'active':''}}">
                        <a class="" href="{{ route('admin.school') }}">
                            <i class="fa fa-graduation-cap" style="color: #bc81ff"></i>
                            <span> All Schools</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'add'?'active':''}}">
                        <a class="" href="{{ route('admin.school.add') }}">
                            <i class="fa fa-plus-circle" style="color: #1107ff"></i>
                            <span> Add School</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'owners'?'active':''}}">
                        <a class="" href="{{ route('admin.owner') }}">
                            <i class="fa fa-user" style="color: #ffb4d2"></i>
                            <span>School Owners</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="fa fa-paperclip" style="color: #ffc38c"></i>
                    <span>Report</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub" style="{{strtolower(Request::segment(2)) == 'rep'?'display:block':''}}">
                    <li class="{{ strtolower(Request::segment(3)) == 'report'?'active':''}}">
                        <a class="" href="{{ route('admin.report') }}">
                            <i class="fa fa-file" style="color: #0fff72"></i>
                            <span>Annual Report</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'gen_report'?'active':''}}">
                        <a class="" href="{{ route('admin.gen.report') }}">
                            <i class="fa fa-file-archive-o" style="color: #a70dff"></i>
                            <span>Generate Report</span>
                        </a>
                    </li>
                    <li class="{{ strtolower(Request::segment(3)) == 'advert'?'active':''}}">
                        <a class="" href="{{ route('admin.advert') }}">
                            <i class="fa fa-adn" style="color: #407fff"></i>
                            <span>Advert</span>
                        </a>
                    </li>
                </ul>
            </li>

        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->

resources/views/Partials/admin/_header.blade.php
<header class="header dark-bg">

    <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom">
            <i class="icon_menu"></i>
        </div>
    </div>

    <!--logo start-->
    <a href="{{ route('admin.index') }}" class="logo">
        <img src="{{ asset('/images/logo.png') }}" alt="" width="30px" height="35px">
        <span class="lite"><b>GNAPS</b></span>
    </a>
    <!--logo end-->


    <div class="top-nav notification-row">

        <ul class="nav pull-right top-menu">


            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    @if(Auth::Check())
                        <span class="profile-ava">
                                <img alt="" src="{{ Auth::user()->image }}" width="30" height="30">
                        </span>
                        <span class="username">{{ Auth::user()->first_name }} </span>
                        <b class="caret"></b>
                    @endif
                </a>
                <ul class="dropdown-menu extended logout">
                    <div class="log-arrow-up"></div>

                    <li class="eborder-top">
                        <a href="#profile" data-toggle="modal">
                            <i class="icon_profile"></i> My Profile
                        </a>
                    </li>

                    <li>
                        <a href="#change_password" data-toggle="modal">
                            <i class="icon_key_alt"></i> Change Password
                        </a>
                    </li>

                    <li>
                        <a href="{{ route('logout') }}">
                            <i class="icon_lock_alt"></i> Log Out
                        </a>
                    </li>
                </ul>
            </li>

        </ul>
    </div>
</header>
<!--header end-->

<profile-component userinfo="{{ Auth::user() }}"></profile-component>

resources/views/Partials/admin/_script.blade.php
<!-- javascripts -->
<script src="{{ asset('/js/app.js')}}"></script>
<script src="{{ asset('/admin/js/jquery.js') }}"></script>
<script src="{{ asset('/admin/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/admin/js/jquery.scrollTo.min.js') }}"></script>
{{--<script src="{{ asset('/admin/js/jquery.nice.scroll.js') }}"></script>--}}

<script src="{{ asset('/admin/js/scripts.js') }}"></script>
{{--<script src="{{ asset('/js/style.js') }}"></script>--}}
<script src="{{ asset('/admin/js/jquery.nicescroll.js') }}"></script>

{{--window.addEventListener('wheel', { passive: false })--}}
{{--<script src="{{ asset('/admin/js/jquery-3.4.1.js') }}"></script>--}}

resources/views/Partials/admin/_style.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
<meta name="author" content="GeeksLabs">
<meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
<link rel="shortcut icon" href="{{ asset('/images/logo.png') }}">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">


<title>GNAPS | @yield('title')</title>


<link href="{{ asset('/admin/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('/admin/css/bootstrap-theme.css') }}" rel="stylesheet">
<link href="{{ asset('/admin/css/elegant-icons-style.css') }}" rel="stylesheet"/>
<link href="{{ asset('/page/lib/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
<link href="{{ asset('/admin/css/style.css') }}" rel="stylesheet">
<link href="{{ asset('/admin/css/style-responsive.css') }}" rel="stylesheet" />